services:
  devcontainer:
    build: .
    volumes:
      - ./../:/workspaces/a2a-example
      - devcontainer-zshhistory:/root/commandhistory/.zsh_history
      # Forward docker socket to allow docker commands to be run from within the container
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
volumes:
  devcontainer-zshhistory:
